### ISSUE TITLE
Mode to snapshot all Ethereum objects at a block height

### ISSUE THREAD

**Issue by ashwinphatak** [cerc-io/ipld-eth-state-snapshot#44]
Currently the snapshot only captures the full state and storage tries as well as all codehash => code mappings, and links them up to a header in eth.header_cids. We do not load and index the other data at this block height e.g. txs, rcts, logs.

- [ ] eth.uncle_cids
- [ ] eth.transaction_cids
- [ ] eth.receipt_cids
- [ ] eth.access_list_elements
- [ ] eth.log_cids

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/ipld-eth-state-snapshot/issues/3
